//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class YemekSiparisEntities : DbContext
    {
        public YemekSiparisEntities()
            : base("name=YemekSiparisEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Adres> Adres { get; set; }
        public virtual DbSet<Ilce> Ilce { get; set; }
        public virtual DbSet<Kullanici> Kullanici { get; set; }
        public virtual DbSet<Menu> Menu { get; set; }
        public virtual DbSet<Restoran> Restoran { get; set; }
        public virtual DbSet<Sehir> Sehir { get; set; }
        public virtual DbSet<Siparis> Siparis { get; set; }
        public virtual DbSet<RestoranListele2> RestoranListele2 { get; set; }
        public virtual DbSet<Urun> Urun { get; set; }
        public virtual DbSet<UrunMenu> UrunMenu { get; set; }
        public virtual DbSet<UrunMenusu> UrunMenusu { get; set; }
        public virtual DbSet<SiparisListe> SiparisListe { get; set; }
    
        public virtual ObjectResult<UrunMenusuL_Result> UrunMenusuL()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UrunMenusuL_Result>("UrunMenusuL");
        }
    
        public virtual ObjectResult<UrunMenusuP_Result> UrunMenusuP()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UrunMenusuP_Result>("UrunMenusuP");
        }
    }
}
