//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RestoranListele2
    {
        public int RestoranKodu { get; set; }
        public string RestoranAdi { get; set; }
        public string Tanim { get; set; }
        public string DetayliBilgi { get; set; }
        public string SehirAdi { get; set; }
        public string IlceAdi { get; set; }
        public Nullable<int> MenuKodu { get; set; }
        public Nullable<int> YetkiliID { get; set; }
    }
}
