//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Restoran
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Restoran()
        {
            this.Siparis = new HashSet<Siparis>();
        }
    
        public int RestoranKodu { get; set; }
        public string RestoranAdi { get; set; }
        public Nullable<int> AdresKodu { get; set; }
        public Nullable<int> MenuKodu { get; set; }
        public string Tanim { get; set; }
        public string DetayliBilgi { get; set; }
        public Nullable<int> YetkiliID { get; set; }
    
        public virtual Adres Adres { get; set; }
        public virtual Menu Menu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Siparis> Siparis { get; set; }
        public virtual Kullanici Kullanici { get; set; }
    }
}
