//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Siparis
    {
        public int SiparisKodu { get; set; }
        public Nullable<int> ToplamTutar { get; set; }
        public Nullable<int> RestoranKodu { get; set; }
        public Nullable<int> KullaniciID { get; set; }
        public Nullable<int> UMKodu { get; set; }
        public Nullable<int> Tamamlandi { get; set; }
    
        public virtual Restoran Restoran { get; set; }
        public virtual Kullanici Kullanici { get; set; }
        public virtual UrunMenu UrunMenu { get; set; }
    }
}
